export type NotificationType =
  | "DEVICE_DEGRADED"
  | "DEVICE_OFFLINE"
  | "ENROLLMENT_CONFLICT"
  | "DELETION_COMPLETED"
  | "DELETION_FAILED"
  | "RETENTION_DEADLINE_APPROACHING"
  | "EVENT_AUTO_CLOSED";
